version: "3"
services:

  lisk-explorer:
    image: lisk/explorer
    ports:
      - "127.0.0.1:6040:6040"
    networks:
      - lisk-explorer
      - localhost
    restart: on-failure
    environment:
      - SERVICE_ENDPOINT=https://service:9901

networks:
  lisk-explorer:
  localhost:
    external: true
