version: "3"
services:

  lisk-explorer:
    image: lisk/explorer:latest
    depends_on:
      - explorer-cache
    networks:
      - lisk-explorer
    restart: on-failure
    environment:
      - LISK_URL_HTTP=${EXPLORER_LISK_HTTP_URL}
      - LISK_URL_WS=${EXPLORER_LISK_WS_URL}
      - REDIS_HOST=explorer-cache
      - FREEGEOIP_URL=https://geoip.lisk.io
      - ENABLE_MARKET_FEATURES=true

  explorer-cache:
    image: redis:alpine
    networks:
      - lisk-explorer
    restart: on-failure

  explorer-cache-candles:
    image: lisk/explorer:latest
    depends_on:
      - explorer-cache
    networks:
      - lisk-explorer
    environment:
      - REDIS_HOST=explorer-cache
    command: ./node_modules/grunt-cli/bin/grunt candles:build


networks:
  lisk-explorer:


