version: "3"
services:

  lisk-explorer:
    image: lisk/explorer:latest
    depends_on:
      - explorer-cache
      - freegeoip
    networks:
      - lisk-explorer
    restart: on-failure
    environment:
      - LISK_HOST=${EXPLORER_LISK_HOST}
      - LISK_PORT=${EXPLORER_LISK_PORT}
      - REDIS_HOST=explorer-cache
      - FREEGEOIP_HOST=freegeoip

  explorer-cache:
    image: redis:alpine
    networks:
      - lisk-explorer
    restart: on-failure

  explorer-cache-candles:
    image: lisk/explorer:latest
    depends_on:
      - explorer-cache
    networks:
      - lisk-explorer
    environment:
      - REDIS_HOST=explorer-cache
    command: ./node_modules/grunt-cli/bin/grunt candles:build

  freegeoip:
    image: fiorix/freegeoip
    networks:
      - lisk-explorer
    restart: on-failure


networks:
  lisk-explorer:


